language: java
sudo: required
jdk:
  - openjdk13

branches:
  only:
    - develop

before_script:
  - "curl -O https://download.clojure.org/install/linux-install-1.10.1.507.sh"
  - "chmod +x linux-install-1.10.1.507.sh"
  - "sudo ./linux-install-1.10.1.507.sh"
  - "clojure -Sdescribe"

cache:
  directories:
    - $HOME/.m2
    - $HOME/.cljs
    - node_modules
    - .cpcache
    - cljs-test-runner-out

script:
  - "clojure -A:test"