# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2

jobs:

  build:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:openjdk-13-tools-deps-1.10.1.502-buster

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:

      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - add_ssh_keys:
          fingerprints:
            - "0e:9d:ea:53:87:06:1d:04:bb:7a:d8:77:99:a3:83:71"

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "deps.edn" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: clojure -Stree

      - save_cache:
          paths:
            - ~/.m2
            - .cpcache
            - node_modules
          key: v1-dependencies-{{ checksum "deps.edn" }}

      # run tests!
      - run: clojure -A:test
